name: conductify
description: "A hand gesture recognition project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.0+1 
  http: ^0.13.4 
  audioplayers: ^5.2.1
  flutter_web_auth: ^0.5.0
  uri: ^1.0.0
  flutter_secure_storage: ^9.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hgrlogo.jpg
    - assets/conductify_logo.png
  